// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
	"meta": {
		"title": "React Gaming 101",
		"description": "React Gaming 101 is a project to learn React by building a real-world application."
	},
	"theme": {
		"label": "Theme",
		"system": "System",
		"light": "Light",
		"dark": "Dark"
	},
	"locale": {
		"label": "Language",
		"zh-TW": "繁體中文",
		"zh-CN": "简体中文",
		"en-US": "English"
	},
	"action": {
		"confirm": "Confirm",
		"cancel": "Cancel",
		"connect-wallet": "Connect Wallet",
		"reset": "Reset",
		"active": "Active",
		"clear": "Clear",
		"back": "Back",
		"back-to-previous": "Back to previous",
		"back-to-home": "Back to home",
		"skip": "Skip",
		"experience": "Experience",
		"copy": "Copy",
		"copied": "Copied",
		"retry": "Retry",
		"send": "Send",
		"pause": "Pause",
		"go-to": "Go to",
		"login": "Login",
		"update": "Update",
		"edit": "Edit",
		"publish": "Publish",
		"save-and-back": "Save and back",
		"play": "Play"
	},
	"validation": {
		"required": "This field is required",
		"invalid-type": "Invalid type",
		"pattern": {
			"email": "Invalid email format",
			"url": "Invalid URL format",
			"wallet-address": "Invalid wallet address",
			"number": "Invalid number format",
			"more-than-0": "Must be greater than 0",
			"more-than-min": "Must be greater than {min}"
		}
	},
	"utils": {
		"more-then-item": "more then {item}",
		"enter": "Please enter",
		"no-data": "No data",
		"no-result": "No result found",
		"searching": "Searching...",
		"unable-to-load": {
			"title": "Unable to load data",
			"description": "Please try again later, or check your network connection."
		},
		"too-many-requests": {
			"default": "You have made too many requests, please try again later",
			"title": "Too many requests",
			"description": "Please try again later",
			"with-limit": "You have made {limit} requests, please try again later"
		},
		"leave-site": "You are about to leave our website and go to",
		"limit-characters": "{current}/{limit} characters",
		"default": "Default",
		"all": "All",
		"view-all": "View all",
		"unsaved-changes": {
			"title": "Unsaved changes",
			"description": "Leaving will discard your recent adjustments.",
			"discard": "Discard Changes"
		},
		"delete": {
			"title": "Delete",
			"description": "Are you sure you want to delete this item?"
		}
	},
	"commons": {
		"error": {
			"title": "Error",
			"description": "Please try again later",
			"retry": "Retry"
		},
		"not-found": {
			"title": "Page not found",
			"description": "The page you are trying to access may have been deleted or does not exist"
		},
		"forbidden": {
			"title": "Forbidden",
			"description": "You are not allowed to access this page"
		}
	},
	"routes": {
		"tic-tac-toe": {
			"title": "Tic Tac Toe",
			"description": "Tic Tac Toe is a simple board game where players take turns placing X or O on a square grid. The first player to get 3 in a row wins."
		},
		"roulette": {
			"title": "Roulette",
			"description": "Roulette is a simple game where players spin a wheel and the pointer lands on a reward."
		}
	},
	"tic-tac-toe": {
		"description": "Tic Tac Toe is a simple board game where players take turns placing X or O on a {size}x{size} grid. The first player to get 3 in a row wins.",
		"set-size": "Set board size",
		"winner": "Player {winner} wins!",
		"draw": "Draw!",
		"current-player": "Current player: {player}",
		"reset": "Reset",
		"size-description": "Please enter a number between 3 and 10"
	}
};
export default messages;